force-app/main/default/objects/Condition__c/Condition__c.object-meta.xml
<CustomObject>
    <label>Condition</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Condition Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition__c/fields/Element__c.field-meta.xml
<CustomField>
    <fullName>Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Element</label>
    <referenceTo>Element__c</referenceTo>
    <relationshipLabel>Conditions</relationshipLabel>
    <relationshipName>Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Condition__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Step</label>
    <referenceTo>Step__c</referenceTo>
    <relationshipLabel>Conditions</relationshipLabel>
    <relationshipName>Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Condition__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Condition&apos;s stored value assigned by the user</description>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Element__c/Element__c.object-meta.xml
<CustomObject>
    <label>Element</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Element Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Element__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>Step</label>
    <referenceTo>Step__c</referenceTo>
    <relationshipLabel>Elements</relationshipLabel>
    <relationshipName>Elements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Step__c/Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Step Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ConditionController.cls
public with sharing class ConditionController {
    @AuraEnabled(cacheable=true)
    public static List<Condition__c> getConditionsStep(String strId){
        try {
            Id key = strId;
            
            return [SELECT Value__c, Label__c
                    FROM Condition__c
                    WHERE Step__r.Id = :key];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<Condition__c> getConditionsElement(String strId){
        try {
            Id key = strId;
            return [SELECT Value__c, Label__c
                    FROM Condition__c
                    WHERE Element__r.Id = :key];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}