force-app/main/default/objects/Condition__c/Condition__c.object-meta.xml
<CustomObject>
    <label>Condition</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Condition Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition__c/fields/Element__c.field-meta.xml
<CustomField>
    <fullName>Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Element</label>
    <referenceTo>Element__c</referenceTo>
    <relationshipLabel>Conditions</relationshipLabel>
    <relationshipName>Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Condition__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Step</label>
    <referenceTo>Step__c</referenceTo>
    <relationshipLabel>Conditions</relationshipLabel>
    <relationshipName>Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Condition__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Condition&apos;s stored value assigned by the user</description>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Element__c/Element__c.object-meta.xml
<CustomObject>
    <label>Element</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Element Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Element__c/fields/Element_Type__c.field-meta.xml
<CustomField>
    <fullName>Element_Type__c</fullName>
    <description>The type of element defined by the user</description>
    <label>Element Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Element__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>Step</label>
    <referenceTo>Step__c</referenceTo>
    <relationshipLabel>Elements</relationshipLabel>
    <relationshipName>Elements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Element__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of element defined by the user</description>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Step__c/Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Step Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ConditionControllerTest.cls
@isTest
public class ConditionControllerTest {
    @TestSetup
    static void makeData(){
        Step__c s = new Step__c(Title__c='StepForConditionTest');
        insert s;
        Element__c e = new Element__c(Step__c=s.Id, Title__c='ElementForConditionTest', Element_Type__c='TestElement');
        insert e;
        Condition__c c_step = new Condition__c(Step__c=s.Id, Value__c='TestCondition');
        insert c_step;
        Condition__c c_element = new Condition__c(Element__c=e.Id, Value__c='TestCondition');
        insert c_element;
    }

    @isTest static void getConditionsWithStep() {
        Test.startTest();
        Step__c query_step = [SELECT Id FROM Step__c WHERE Title__c ='StepForConditionTest'];
        ConditionController.getConditionsStep(query_step.Id);
        Test.stopTest();
    }

    @isTest static void getConditionsWithElement() {
        Test.startTest();
        Element__c query_element = [SELECT Id From Element__c WHERE Title__c = 'ElementForConditionTest'];
        ConditionController.getConditionsElement(query_element.Id);
        Test.stopTest();
    }

    @isTest static void getConditionsFailsWithStep() {
        Test.startTest();
        try {
            ConditionController.getConditionsStep('test');
        } catch(Exception e) {
            System.debug(e.getMessage());
        }
        Test.stopTest();
    }

    @isTest static void getConditionsFailsWithElement() {
        Test.startTest();
        try {
            ConditionController.getConditionsElement('test');
            
        } catch(Exception e) {
            System.debug(e.getMessage());
        }
        Test.stopTest();
    }
}